services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data

  go-server:
    build: .
    container_name: go-server
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - GO_ENV=development
    depends_on:
      - postgres
    command: sh -c "go run migrate/migrate.go && air"

volumes:
  postgres: